'use strict';

const mongoose = require('mongoose');
const { EDUCATION_LEVELS, GRADES, QUESTION_TYPES, ENGLISH_SKILLS, COURSE_CATEGORIES, SOURCE_TYPES, sourceRefSchema } = require('../config/platform-constants');

const options = collection => ({ timestamps: true, collection });
const sourceRef = sourceRefSchema();
const profileSchema = new mongoose.Schema({ username: { type: String, required: true, unique: true, index: true }, fullName: String, avatar: String, dob: { day: Number, month: Number, year: Number }, guardianUsername: String, consent: { type: mongoose.Schema.Types.Mixed, default: {} } }, options('profiles'));
const educationProfileSchema = new mongoose.Schema({ username: { type: String, required: true, unique: true, index: true }, educationLevel: String, grade: { type: Number, min: 1, max: 12, default: null }, institution: String, universityName: String, facultyName: String, fieldName: String, disciplineGroupName: String, majorName: String, specializationName: String, trainingProgramName: String, universityId: mongoose.Schema.Types.ObjectId, facultyId: mongoose.Schema.Types.ObjectId, fieldId: mongoose.Schema.Types.ObjectId, disciplineGroupId: mongoose.Schema.Types.ObjectId, majorId: mongoose.Schema.Types.ObjectId, specializationId: mongoose.Schema.Types.ObjectId, trainingProgramId: mongoose.Schema.Types.ObjectId, cohort: String, academicYear: String, semester: String, educationStatus: String, provenance: { type: mongoose.Schema.Types.Mixed, default: {} } }, options('educationProfiles'));
const learningProfileSchema = new mongoose.Schema({ username: { type: String, required: true, unique: true, index: true }, goals: { type: [String], default: [] }, skills: { type: mongoose.Schema.Types.Mixed, default: {} }, survey: { type: mongoose.Schema.Types.Mixed, default: {} }, diagnostics: { type: mongoose.Schema.Types.Mixed, default: {} }, inference: { type: mongoose.Schema.Types.Mixed, default: {} }, aiPreferences: { type: mongoose.Schema.Types.Mixed, default: {} }, learningPlanId: mongoose.Schema.Types.ObjectId }, options('platformLearningProfiles'));

const sourceRegistrySchema = new mongoose.Schema({
    sourceName: { type: String, required: true, trim: true }, sourceType: { type: String, default: 'official' },
    documentName: { type: String, required: true }, documentNumber: { type: String, default: '' }, url: { type: String, default: '' },
    version: { type: String, default: '' }, effectiveDate: { type: Date, default: null }, verifiedAt: { type: Date, default: null },
    verification: { type: String, enum: ['unverified', 'title_verified', 'full_text_verified'], default: 'unverified' }, notes: { type: String, default: '' }, status: { type: String, enum: ['ACTIVE', 'ARCHIVED'], default: 'ACTIVE' }
}, options('sourceRegistry'));

const curriculumVersionSchema = new mongoose.Schema({
    code: { type: String, required: true }, version: { type: String, required: true }, status: { type: String, enum: ['DRAFT', 'ACTIVE', 'ARCHIVED'], default: 'DRAFT' },
    educationLevel: { type: String, enum: EDUCATION_LEVELS }, grades: { type: [Number], default: [] }, sourceRef: { type: sourceRef, default: {} }, objectives: { type: [String], default: [] }, metadata: { type: mongoose.Schema.Types.Mixed, default: {} }
}, options('curriculumVersions'));
curriculumVersionSchema.index({ code: 1, version: 1 }, { unique: true });

const curriculumContentSchema = new mongoose.Schema({
    curriculumVersionId: { type: mongoose.Schema.Types.ObjectId, required: true, index: true }, type: { type: String, enum: ['SUBJECT', 'DOMAIN', 'UNIT', 'LESSON'], required: true },
    parentId: { type: mongoose.Schema.Types.ObjectId, default: null, index: true }, courseId: { type: mongoose.Schema.Types.ObjectId, default: null, index: true }, code: { type: String, required: true }, title: { type: String, required: true }, description: String, grade: { type: Number, min: 1, max: 12, default: null }, educationLevel: { type: String, enum: EDUCATION_LEVELS }, subjectId: { type: String, default: '' }, objectives: { type: [String], default: [] }, theory: mongoose.Schema.Types.Mixed, theorySections: { type: [mongoose.Schema.Types.Mixed], default: [] }, audioAssetId: { type: mongoose.Schema.Types.ObjectId, default: null }, examples: { type: [mongoose.Schema.Types.Mixed], default: [] }, media: { type: [mongoose.Schema.Types.Mixed], default: [] }, activities: { type: [mongoose.Schema.Types.Mixed], default: [] }, practiceIds: { type: [mongoose.Schema.Types.ObjectId], default: [] }, assessmentIds: { type: [mongoose.Schema.Types.ObjectId], default: [] }, knowledge: { type: [String], default: [] }, skills: { type: [String], default: [] }, outcomes: { type: [mongoose.Schema.Types.Mixed], default: [] }, lessonTestId: { type: mongoose.Schema.Types.ObjectId, default: null }, prerequisiteIds: { type: [mongoose.Schema.Types.ObjectId], default: [] }, estimatedMinutes: Number, difficulty: String, references: { type: [mongoose.Schema.Types.Mixed], default: [] }, generationMetadata: { type: mongoose.Schema.Types.Mixed, default: {} }, status: { type: String, enum: ['DRAFT', 'PUBLISHED', 'ARCHIVED'], default: 'DRAFT' }, sourceRef: { type: sourceRef, default: {} }, payload: { type: mongoose.Schema.Types.Mixed, default: {} }
}, options('curriculumContent'));
curriculumContentSchema.index({ curriculumVersionId: 1, type: 1, code: 1 }, { unique: true });

const universitySchema = new mongoose.Schema({ code: { type: String, required: true }, name: { type: String, required: true }, shortName: String, type: String, description: String, website: String, status: { type: String, default: 'ACTIVE' } }, options('universities'));
const facultySchema = new mongoose.Schema({ universityId: { type: mongoose.Schema.Types.ObjectId, required: true, index: true }, code: String, name: { type: String, required: true }, description: String, status: { type: String, default: 'ACTIVE' } }, options('faculties'));
const fieldSchema = new mongoose.Schema({ code: { type: String, required: true }, name: { type: String, required: true }, description: String, status: { type: String, default: 'ACTIVE' } }, options('fields'));
const disciplineGroupSchema = new mongoose.Schema({ fieldId: { type: mongoose.Schema.Types.ObjectId, required: true, index: true }, code: String, name: { type: String, required: true }, description: String }, options('disciplineGroups'));
const majorSchema = new mongoose.Schema({ disciplineGroupId: { type: mongoose.Schema.Types.ObjectId, required: true, index: true }, code: String, name: { type: String, required: true }, degreeLevel: String, duration: Number, status: { type: String, default: 'ACTIVE' } }, options('majors'));
const specializationSchema = new mongoose.Schema({ majorId: { type: mongoose.Schema.Types.ObjectId, required: true, index: true }, code: String, name: { type: String, required: true }, description: String }, options('specializations'));
const trainingProgramSchema = new mongoose.Schema({ institutionId: { type: mongoose.Schema.Types.ObjectId, required: true, index: true }, facultyId: mongoose.Schema.Types.ObjectId, fieldId: mongoose.Schema.Types.ObjectId, disciplineGroupId: mongoose.Schema.Types.ObjectId, majorId: mongoose.Schema.Types.ObjectId, specializationId: mongoose.Schema.Types.ObjectId, programName: { type: String, required: true }, version: { type: String, default: '1' }, academicYear: String, cohort: String, totalCredits: Number, learningOutcomes: { type: [mongoose.Schema.Types.Mixed], default: [] }, graduationRequirements: { type: mongoose.Schema.Types.Mixed, default: {} }, educationStandard: { type: mongoose.Schema.Types.Mixed, default: {} }, sourceRef: { type: sourceRef, default: {} }, status: { type: String, enum: ['DRAFT', 'ACTIVE', 'ARCHIVED'], default: 'DRAFT' } }, options('trainingPrograms'));
const courseSchema = new mongoose.Schema({
    programId: { type: mongoose.Schema.Types.ObjectId, default: null, index: true }, institutionId: { type: mongoose.Schema.Types.ObjectId, default: null, index: true }, facultyId: { type: mongoose.Schema.Types.ObjectId, default: null, index: true }, majorId: { type: mongoose.Schema.Types.ObjectId, default: null, index: true }, specializationId: { type: mongoose.Schema.Types.ObjectId, default: null, index: true }, trainingProgramId: { type: mongoose.Schema.Types.ObjectId, default: null, index: true }, curriculumVersionId: { type: mongoose.Schema.Types.ObjectId, default: null, index: true }, educationLevel: { type: String, enum: EDUCATION_LEVELS }, grade: { type: Number, min: 1, max: 12, default: null }, subjectId: String, domainId: mongoose.Schema.Types.ObjectId, unitIds: { type: [mongoose.Schema.Types.ObjectId], default: [] }, code: { type: String, required: true }, name: { type: String, required: true }, credits: Number, semester: Number, year: Number, academicYear: String, required: Boolean, optional: Boolean, prerequisiteCourses: { type: [mongoose.Schema.Types.ObjectId], default: [] }, coRequisiteCourses: { type: [mongoose.Schema.Types.ObjectId], default: [] }, category: { type: String, enum: COURSE_CATEGORIES, default: 'OTHER' }, description: String, objectives: { type: [String], default: [] }, learningOutcomes: { type: [mongoose.Schema.Types.Mixed], default: [] }, estimatedMinutes: Number, difficulty: String, sourceRef: { type: sourceRef, default: {} }, syllabus: { type: mongoose.Schema.Types.Mixed, default: {} }, kind: { type: String, enum: ['CANONICAL', 'PERSONAL_AI', 'AI_DRAFT'], default: 'CANONICAL' }, ownerUsername: { type: String, default: '', index: true }, personalizedFor: { type: mongoose.Schema.Types.Mixed, default: {} }, aiGeneration: { type: mongoose.Schema.Types.Mixed, default: {} }, sourceCourseId: { type: mongoose.Schema.Types.ObjectId, default: null, index: true }, contentCompleteness: { type: Number, default: 0, min: 0, max: 100 }, status: { type: String, default: 'ACTIVE' } }, options('courses'));
courseSchema.index({ ownerUsername: 1, kind: 1, status: 1 });
courseSchema.index({ majorId: 1, trainingProgramId: 1, status: 1 });
courseSchema.index({ educationLevel: 1, grade: 1, subjectId: 1, status: 1 });

const questionSchema = new mongoose.Schema({ code: { type: String, required: true }, source: { type: sourceRef, default: {} }, curriculumVersionId: mongoose.Schema.Types.ObjectId, grade: { type: Number, min: 1, max: 12, default: null }, educationLevel: { type: String, enum: EDUCATION_LEVELS }, institutionId: mongoose.Schema.Types.ObjectId, majorId: mongoose.Schema.Types.ObjectId, courseId: mongoose.Schema.Types.ObjectId, lessonId: mongoose.Schema.Types.ObjectId, subjectId: String, type: { type: String, enum: QUESTION_TYPES, required: true }, prompt: { type: String, required: true }, media: { type: mongoose.Schema.Types.Mixed, default: {} }, options: { type: [mongoose.Schema.Types.Mixed], default: [] }, answer: mongoose.Schema.Types.Mixed, acceptedAnswers: { type: [mongoose.Schema.Types.Mixed], default: [] }, rubric: { type: mongoose.Schema.Types.Mixed, default: {} }, explanation: String, points: { type: Number, default: 1 }, difficulty: String, cognitiveLevel: String, skill: String, tags: { type: [String], default: [] }, status: { type: String, enum: ['DRAFT', 'REVIEW', 'PUBLISHED', 'ARCHIVED'], default: 'DRAFT' }, version: { type: Number, default: 1 }, createdBy: mongoose.Schema.Types.ObjectId, updatedBy: mongoose.Schema.Types.ObjectId }, options('questions'));
questionSchema.index({ subjectId: 1, grade: 1, type: 1, status: 1 });
const assessmentSchema = new mongoose.Schema({ code: { type: String, required: true }, title: { type: String, required: true }, educationLevel: String, grade: { type: Number, min: 1, max: 12, default: null }, curriculumVersionId: mongoose.Schema.Types.ObjectId, subjectId: String, courseId: mongoose.Schema.Types.ObjectId, lessonId: mongoose.Schema.Types.ObjectId, sections: { type: [mongoose.Schema.Types.Mixed], default: [] }, assessmentType: { type: String, enum: ['LESSON_TEST', 'CHAPTER_TEST', 'MIDTERM', 'FINAL', 'MOCK', 'DIAGNOSTIC', 'FREE_TEST'], default: 'FINAL', index: true }, questionIds: { type: [mongoose.Schema.Types.ObjectId], default: [] }, questionPool: { type: [mongoose.Schema.Types.ObjectId], default: [] }, durationSeconds: Number, attemptLimit: Number, passingScore: Number, randomization: { type: mongoose.Schema.Types.Mixed, default: {} }, scoring: { type: mongoose.Schema.Types.Mixed, default: {} }, reviewSettings: { type: mongoose.Schema.Types.Mixed, default: {} }, version: { type: String, default: '1' }, publicationStatus: { type: String, enum: ['DRAFT', 'PUBLISHED', 'ARCHIVED'], default: 'DRAFT' }, sourceRef: { type: sourceRef, default: {} } }, options('assessments'));
const assessmentAttemptSchema = new mongoose.Schema({ assessmentId: { type: mongoose.Schema.Types.ObjectId, required: true, index: true }, username: { type: String, required: true, index: true }, startedAt: { type: Date, default: Date.now }, expiresAt: Date, submittedAt: Date, status: { type: String, enum: ['IN_PROGRESS', 'SUBMITTED', 'EXPIRED', 'REVIEW_REQUIRED'], default: 'IN_PROGRESS' }, answers: { type: mongoose.Schema.Types.Mixed, default: {} }, score: Number, result: { type: mongoose.Schema.Types.Mixed, default: {} } }, options('assessmentAttempts'));
const surveySchema = new mongoose.Schema({ title: { type: String, required: true }, description: String, targetLevel: String, version: { type: String, default: '1' }, sourceRef: { type: sourceRef, default: {} }, questions: { type: [mongoose.Schema.Types.Mixed], default: [] }, status: { type: String, enum: ['DRAFT', 'PUBLISHED', 'ARCHIVED'], default: 'DRAFT' } }, options('surveys'));
const surveyAttemptSchema = new mongoose.Schema({ surveyId: mongoose.Schema.Types.ObjectId, surveyVersion: { type: String, default: '1' }, username: { type: String, index: true }, answers: { type: mongoose.Schema.Types.Mixed, default: {} }, result: { type: mongoose.Schema.Types.Mixed, default: {} }, submittedAt: Date }, options('surveyAttempts'));
const placementTestSchema = new mongoose.Schema({ code: { type: String, required: true }, title: String, target: String, version: String, skillSections: { type: [mongoose.Schema.Types.Mixed], default: [] }, sourceRef: { type: sourceRef, default: {} }, status: { type: String, default: 'DRAFT' } }, options('placementTests'));
const placementAttemptSchema = new mongoose.Schema({ placementTestId: mongoose.Schema.Types.ObjectId, username: { type: String, index: true }, answers: { type: mongoose.Schema.Types.Mixed, default: {} }, scores: { type: mongoose.Schema.Types.Mixed, default: {} }, recommendation: { type: mongoose.Schema.Types.Mixed, default: {} }, submittedAt: Date }, options('placementAttempts'));
const learningPlanSchema = new mongoose.Schema({ username: { type: String, required: true, index: true }, educationStage: String, age: Number, educationStatus: String, currentGrade: { type: Number, min: 1, max: 12, default: null }, target: { type: mongoose.Schema.Types.Mixed, default: {} }, curriculumVersionId: mongoose.Schema.Types.ObjectId, version: { type: Number, default: 1 }, generatedAt: { type: Date, default: Date.now }, status: { type: String, enum: ['ACTIVE', 'ARCHIVED'], default: 'ACTIVE' }, subjects: { type: [mongoose.Schema.Types.Mixed], default: [] }, milestones: { type: [mongoose.Schema.Types.Mixed], default: [] }, weeklyPlan: { type: [mongoose.Schema.Types.Mixed], default: [] }, diagnostics: { type: mongoose.Schema.Types.Mixed, default: {} }, recommendations: { type: [mongoose.Schema.Types.Mixed], default: [] } }, options('learningPlans'));
const skillMasterySchema = new mongoose.Schema({ username: { type: String, index: true }, skill: { type: String, required: true }, subjectId: String, courseId: mongoose.Schema.Types.ObjectId, status: { type: String, enum: ['NOT_STARTED', 'LEARNING', 'PRACTICING', 'MASTERED', 'REVIEW_REQUIRED'], default: 'NOT_STARTED' }, accuracy: Number, attempts: Number, lastAttempt: Date, averageScore: Number, recentScore: Number, timeSpent: Number, streak: Number, reviewDueAt: Date }, options('skillMastery'));
const englishAssessmentSchema = new mongoose.Schema({ username: { type: String, index: true }, exam: { type: String, enum: ['TOEIC', 'IELTS'] }, variant: { type: String, default: '' }, skillScores: { type: mongoose.Schema.Types.Mixed, default: {} }, overallEstimate: Number, scoreEvidence: { type: mongoose.Schema.Types.Mixed, default: {} }, rubricVersion: String, assessmentVersion: String, sourceRef: { type: sourceRef, default: {} } }, options('englishAssessments'));
const notificationSchema = new mongoose.Schema({ recipient: { type: String, index: true }, type: String, title: String, message: String, priority: String, data: { type: mongoose.Schema.Types.Mixed, default: {} }, read: { type: Boolean, default: false }, readBy: { type: [String], default: [] }, expiresAt: Date }, options('platformNotifications'));
const auditLogSchema = new mongoose.Schema({ actorId: mongoose.Schema.Types.ObjectId, actorUsername: String, action: String, entityType: String, entityId: String, before: mongoose.Schema.Types.Mixed, after: mongoose.Schema.Types.Mixed, ip: String, userAgent: String }, options('auditLogs'));
const examBlueprintSchema = new mongoose.Schema({ code: { type: String, required: true }, name: { type: String, required: true }, year: Number, subject: String, coverage: { type: mongoose.Schema.Types.Mixed, default: {} }, questionTypes: { type: [String], default: [] }, sections: { type: [mongoose.Schema.Types.Mixed], default: [] }, durationSeconds: Number, scoring: { type: mongoose.Schema.Types.Mixed, default: {} }, version: { type: String, required: true }, sourceType: { type: String, enum: SOURCE_TYPES, default: 'SIMULATION' }, sourceRef: { type: sourceRef, default: {} }, status: { type: String, enum: ['DRAFT', 'PUBLISHED', 'ARCHIVED'], default: 'DRAFT' } }, options('examBlueprints'));
examBlueprintSchema.index({ code: 1, version: 1 }, { unique: true });
const wordImportSchema = new mongoose.Schema({ uploadedBy: String, filename: String, mimeType: String, size: Number, targetType: { type: String, enum: ['COURSE', 'LESSON', 'LECTURE', 'QUESTION', 'QUESTION_BANK', 'ASSESSMENT', 'TOEIC', 'IELTS', 'NATIONAL_EXAM'], required: true }, status: { type: String, enum: ['UPLOADED', 'PREVIEWED', 'VALIDATED', 'COMMITTED', 'REJECTED'], default: 'UPLOADED' }, preview: { type: mongoose.Schema.Types.Mixed, default: {} }, validation: { type: mongoose.Schema.Types.Mixed, default: {} }, committedEntityIds: { type: [mongoose.Schema.Types.ObjectId], default: [] } }, options('wordImports'));
const achievementSchema = new mongoose.Schema({ code: { type: String, required: true }, name: { type: String, required: true }, description: String, event: String, rule: { type: mongoose.Schema.Types.Mixed, default: {} }, status: { type: String, default: 'ACTIVE' } }, options('achievements'));
const rewardSchema = new mongoose.Schema({ code: { type: String, required: true }, name: { type: String, required: true }, type: String, amount: Number, metadata: { type: mongoose.Schema.Types.Mixed, default: {} }, status: { type: String, default: 'ACTIVE' } }, options('rewards'));
const userAchievementSchema = new mongoose.Schema({ username: { type: String, required: true, index: true }, achievementId: { type: mongoose.Schema.Types.ObjectId, required: true }, unlockedAt: { type: Date, default: Date.now }, evidence: { type: mongoose.Schema.Types.Mixed, default: {} } }, options('userAchievements'));
userAchievementSchema.index({ username: 1, achievementId: 1 }, { unique: true });
achievementSchema.index({ code: 1 }, { unique: true });
rewardSchema.index({ code: 1 }, { unique: true });
const rewardGrantSchema = new mongoose.Schema({ username: { type: String, required: true, index: true }, rewardId: mongoose.Schema.Types.ObjectId, sourceEvent: String, amount: Number, grantedAt: { type: Date, default: Date.now }, metadata: { type: mongoose.Schema.Types.Mixed, default: {} } }, options('rewardGrants'));
const gamificationEventSchema = new mongoose.Schema({ username: { type: String, required: true, index: true }, eventType: { type: String, required: true }, referenceId: String, payload: { type: mongoose.Schema.Types.Mixed, default: {} }, processedAt: Date, idempotencyKey: { type: String, required: true } }, options('gamificationEvents'));
gamificationEventSchema.index({ username: 1, idempotencyKey: 1 }, { unique: true });
const learningPathRuleSchema = new mongoose.Schema({ code: { type: String, required: true }, version: { type: String, required: true }, status: { type: String, enum: ['DRAFT', 'ACTIVE', 'ARCHIVED'], default: 'DRAFT' }, scoreThreshold: mongoose.Schema.Types.Mixed, masteryThreshold: mongoose.Schema.Types.Mixed, retry: mongoose.Schema.Types.Mixed, prerequisite: mongoose.Schema.Types.Mixed, reviewInterval: mongoose.Schema.Types.Mixed, difficultyProgression: mongoose.Schema.Types.Mixed, workload: mongoose.Schema.Types.Mixed, examTimeline: mongoose.Schema.Types.Mixed, sourceRef: { type: sourceRef, default: {} } }, options('learningPathRules'));
learningPathRuleSchema.index({ code: 1, version: 1 }, { unique: true });
const englishTestConfigSchema = new mongoose.Schema({ code: { type: String, required: true }, exam: { type: String, enum: ['TOEIC', 'IELTS'], required: true }, variant: String, version: { type: String, required: true }, skills: { type: [String], default: [] }, parts: { type: [mongoose.Schema.Types.Mixed], default: [] }, durationSeconds: mongoose.Schema.Types.Mixed, scoring: { type: mongoose.Schema.Types.Mixed, default: {} }, rubric: { type: mongoose.Schema.Types.Mixed, default: {} }, sourceRef: { type: sourceRef, default: {} }, status: { type: String, enum: ['DRAFT', 'ACTIVE', 'ARCHIVED'], default: 'DRAFT' } }, options('englishTestConfigs'));
englishTestConfigSchema.index({ code: 1, version: 1 }, { unique: true });


const aiContentDraftSchema = new mongoose.Schema({
    type: { type: String, enum: ['COURSE', 'LESSON', 'DIAGNOSTIC', 'ASSESSMENT', 'PRACTICE'], required: true },
    mode: { type: String, enum: ['ADMIN', 'PERSONAL'], required: true },
    ownerUsername: { type: String, default: '', index: true },
    requestedBy: { type: String, default: '' },
    title: { type: String, default: '' },
    prompt: { type: String, default: '' },
    context: { type: mongoose.Schema.Types.Mixed, default: {} },
    draft: { type: mongoose.Schema.Types.Mixed, default: {} },
    validation: { type: mongoose.Schema.Types.Mixed, default: {} },
    status: { type: String, enum: ['DRAFT', 'VALIDATED', 'COMMITTED', 'REJECTED'], default: 'DRAFT', index: true },
    model: { type: String, default: '' },
    promptVersion: { type: String, default: '1' },
    sourceFingerprint: { type: String, index: true },
    committedCourseId: { type: mongoose.Schema.Types.ObjectId, default: null },
    metadata: { type: mongoose.Schema.Types.Mixed, default: {} }
}, options('aiContentDrafts'));
aiContentDraftSchema.index({ mode: 1, ownerUsername: 1, status: 1, createdAt: -1 });
const aiDecisionSchema = new mongoose.Schema({
    username: { type: String, required: true, index: true }, decision: { type: String, required: true }, reason: { type: [String], default: [] }, context: { type: mongoose.Schema.Types.Mixed, default: {} }, output: { type: mongoose.Schema.Types.Mixed, default: {} }, model: { type: String, default: '' }, promptVersion: { type: String, default: '1' }, actionTaken: { type: String, default: '' }, validation: { type: mongoose.Schema.Types.Mixed, default: {} }
}, options('aiDecisionLogs'));
aiDecisionSchema.index({ username: 1, createdAt: -1 });
const aiAudioAssetSchema = new mongoose.Schema({
    ownerUsername: { type: String, default: '', index: true }, courseId: { type: mongoose.Schema.Types.ObjectId, default: null, index: true }, lessonId: { type: mongoose.Schema.Types.ObjectId, default: null, index: true }, textHash: { type: String, required: true }, mimeType: { type: String, default: 'audio/wav' }, model: { type: String, default: '' }, voice: { type: String, default: 'Kore' }, data: { type: Buffer, required: true }, durationSeconds: Number, metadata: { type: mongoose.Schema.Types.Mixed, default: {} }
}, options('aiAudioAssets'));
aiAudioAssetSchema.index({ courseId: 1, lessonId: 1, textHash: 1 }, { unique: true });
const personalCourseNeedSchema = new mongoose.Schema({
    username: { type: String, required: true, index: true }, fingerprint: { type: String, required: true }, need: { type: mongoose.Schema.Types.Mixed, default: {} }, decision: { type: mongoose.Schema.Types.Mixed, default: {} }, status: { type: String, enum: ['OPEN', 'RESOLVED', 'IGNORED'], default: 'OPEN' }, courseId: { type: mongoose.Schema.Types.ObjectId, default: null }
}, options('personalCourseNeeds'));
personalCourseNeedSchema.index({ username: 1, fingerprint: 1 }, { unique: true });
const learningErrorSchema = new mongoose.Schema({
    username: { type: String, required: true, index: true }, fingerprint: { type: String, required: true }, sourceType: { type: String, enum: ['LESSON', 'ASSESSMENT', 'ADAPTIVE_PRACTICE'], required: true }, sourceId: { type: String, default: '' }, grade: { type: Number, min: 1, max: 12, default: null }, subjectId: { type: String, default: '' }, lessonId: { type: String, default: '' }, questionId: { type: String, required: true }, code: { type: String, default: '' }, prompt: { type: String, required: true }, options: { type: [mongoose.Schema.Types.Mixed], default: [] }, correctAnswer: mongoose.Schema.Types.Mixed, userAnswer: mongoose.Schema.Types.Mixed, explanation: { type: String, default: '' }, skill: { type: String, default: 'Kiến thức' }, difficulty: { type: String, default: 'MEDIUM' }, occurrenceCount: { type: Number, default: 0, min: 0 }, correctStreak: { type: Number, default: 0, min: 0 }, resolved: { type: Boolean, default: false, index: true }, resolvedAt: { type: Date, default: null }, lastSeenAt: { type: Date, default: Date.now }, nextReviewAt: { type: Date, default: Date.now, index: true }
}, options('learningErrors'));
learningErrorSchema.index({ username: 1, fingerprint: 1 }, { unique: true });
learningErrorSchema.index({ username: 1, resolved: 1, nextReviewAt: 1 });
const adaptivePracticeSessionSchema = new mongoose.Schema({
    username: { type: String, required: true, index: true }, grade: { type: Number, required: true, min: 1, max: 12 }, subjectId: { type: String, default: '' }, skill: { type: String, default: '' }, mode: { type: String, default: 'ADAPTIVE_V1' }, targetDifficulty: { type: String, enum: ['EASY', 'MEDIUM', 'HARD'], default: 'MEDIUM' }, questionPool: { type: [mongoose.Schema.Types.Mixed], default: [] }, servedQuestionIds: { type: [String], default: [] }, currentQuestionId: { type: String, default: '' }, answers: { type: mongoose.Schema.Types.Mixed, default: {} }, history: { type: [mongoose.Schema.Types.Mixed], default: [] }, correct: { type: Number, default: 0 }, total: { type: Number, default: 0 }, score: { type: Number, default: 0 }, status: { type: String, enum: ['IN_PROGRESS', 'COMPLETED', 'ABANDONED'], default: 'IN_PROGRESS', index: true }, startedAt: { type: Date, default: Date.now }, completedAt: { type: Date, default: null }, recommendation: { type: mongoose.Schema.Types.Mixed, default: {} }
}, options('adaptivePracticeSessions'));
adaptivePracticeSessionSchema.index({ username: 1, status: 1, createdAt: -1 });
const userAudioAssetSchema = new mongoose.Schema({ ownerUsername: { type: String, required: true, index: true }, mimeType: { type: String, default: 'audio/webm' }, data: { type: Buffer, required: true }, sha256: { type: String, required: true }, durationSeconds: Number, metadata: { type: mongoose.Schema.Types.Mixed, default: {} } }, options('userAudioAssets'));
userAudioAssetSchema.index({ ownerUsername: 1, sha256: 1 }, { unique: true });
const aiImageAssetSchema = new mongoose.Schema({ ownerUsername: { type: String, default: '', index: true }, courseId: { type: mongoose.Schema.Types.ObjectId, default: null, index: true }, lessonId: { type: mongoose.Schema.Types.ObjectId, default: null, index: true }, promptHash: { type: String, required: true }, mimeType: { type: String, default: 'image/png' }, model: { type: String, default: '' }, data: { type: Buffer, required: true }, width: Number, height: Number, metadata: { type: mongoose.Schema.Types.Mixed, default: {} } }, options('aiImageAssets'));
aiImageAssetSchema.index({ courseId: 1, lessonId: 1, promptHash: 1 }, { unique: true });
const englishSpeakingAttemptSchema = new mongoose.Schema({ username: { type: String, required: true, index: true }, exam: { type: String, enum: ['TOEIC', 'IELTS'], required: true }, variant: { type: String, default: '' }, task: { type: String, default: 'SPEAKING' }, prompt: { type: String, default: '' }, expectedText: { type: String, default: '' }, audioAssetId: { type: mongoose.Schema.Types.ObjectId, default: null }, transcript: { type: String, default: '' }, scores: { type: mongoose.Schema.Types.Mixed, default: {} }, pronunciation: { type: mongoose.Schema.Types.Mixed, default: {} }, intonation: { type: mongoose.Schema.Types.Mixed, default: {} }, fluency: { type: mongoose.Schema.Types.Mixed, default: {} }, grammar: { type: mongoose.Schema.Types.Mixed, default: {} }, vocabulary: { type: mongoose.Schema.Types.Mixed, default: {} }, feedback: { type: [String], default: [] }, nextPractice: { type: [String], default: [] }, model: { type: String, default: '' }, status: { type: String, enum: ['ANALYZED', 'DEGRADED', 'FAILED'], default: 'ANALYZED' } }, options('englishSpeakingAttempts'));
englishSpeakingAttemptSchema.index({ username: 1, exam: 1, createdAt: -1 });
const codeExecutionAttemptSchema = new mongoose.Schema({ username: { type: String, required: true, index: true }, courseId: { type: mongoose.Schema.Types.ObjectId, default: null, index: true }, lessonId: { type: mongoose.Schema.Types.ObjectId, default: null, index: true }, language: { type: String, required: true }, code: { type: String, required: true }, stdin: { type: String, default: '' }, stdout: { type: String, default: '' }, stderr: { type: String, default: '' }, compileError: { type: String, default: '' }, exitCode: { type: Number, default: null }, timedOut: { type: Boolean, default: false }, runtimeMs: { type: Number, default: 0 }, status: { type: String, enum: ['SUCCESS','ERROR','TIMEOUT','DISABLED'], default: 'SUCCESS' } }, options('codeExecutionAttempts'));
codeExecutionAttemptSchema.index({ username: 1, courseId: 1, createdAt: -1 });
const aiGenerationJobSchema = new mongoose.Schema({ username: { type: String, default: '', index: true }, type: { type: String, enum: ['PERSONAL_COURSE', 'COURSE', 'LESSON', 'ASSESSMENT', 'AUDIO', 'IMAGE', 'SPEAKING_ANALYSIS'], required: true }, status: { type: String, enum: ['QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'WAITING_RETRY'], default: 'QUEUED', index: true }, priority: { type: Number, default: 50, index: true }, progress: { type: Number, default: 0, min: 0, max: 100 }, currentStep: { type: String, default: 'QUEUED' }, model: { type: String, default: '' }, fallbackUsed: { type: Boolean, default: false }, generationTimeMs: { type: Number, default: 0, min: 0 }, payload: { type: mongoose.Schema.Types.Mixed, default: {} }, result: { type: mongoose.Schema.Types.Mixed, default: {} }, attempts: { type: Number, default: 0 }, nextRunAt: { type: Date, default: Date.now, index: true }, lockedAt: { type: Date, default: null }, error: { type: mongoose.Schema.Types.Mixed, default: {} }, idempotencyKey: { type: String, required: true, unique: true }, startedAt: Date, completedAt: Date, finishedAt: Date }, options('aiGenerationJobs'));
aiGenerationJobSchema.index({ status: 1, priority: -1, nextRunAt: 1, createdAt: 1 });
const lessonProgressSchema = new mongoose.Schema({
    username: { type: String, required: true, index: true },
    courseId: { type: mongoose.Schema.Types.ObjectId, required: true, index: true },
    lessonId: { type: mongoose.Schema.Types.ObjectId, required: true, index: true },
    completedSteps: { type: [String], default: [] },
    progressPercent: { type: Number, default: 0, min: 0, max: 100 },
    completed: { type: Boolean, default: false, index: true },
    lastSeenAt: { type: Date, default: Date.now },
    completedAt: { type: Date, default: null },
    timeSpentSeconds: { type: Number, default: 0, min: 0, max: 86400 },
    source: { type: String, default: 'LEARNER_CHECKLIST' }
}, options('lessonProgress'));
lessonProgressSchema.index({ username: 1, lessonId: 1 }, { unique: true });
lessonProgressSchema.index({ username: 1, courseId: 1, completed: 1 });

const aiAmbientInsightSchema = new mongoose.Schema({
    username: { type: String, required: true, index: true }, pageKey: { type: String, required: true, index: true }, eventType: { type: String, default: 'PAGE_VIEW' }, endpoint: { type: String, default: '' }, fingerprint: { type: String, required: true, index: true }, insight: { type: mongoose.Schema.Types.Mixed, default: {} }, model: { type: String, default: '' }, sourceType: { type: String, default: 'GEMINI_AMBIENT_AI' }, generatedAt: { type: Date, default: Date.now, index: true }
}, options('aiAmbientInsights'));
aiAmbientInsightSchema.index({ username: 1, fingerprint: 1 }, { unique: true });
aiAmbientInsightSchema.index({ username: 1, pageKey: 1, createdAt: -1 });

const contentReferenceSchema = new mongoose.Schema({ label: { type: String, required: true, trim: true, maxlength: 180 }, url: { type: String, default: '', maxlength: 1000 }, kind: { type: String, enum: ['LINK', 'BOOK', 'VIDEO', 'FILE', 'IMAGE', 'AUDIO', 'OTHER'], default: 'OTHER' } }, { _id: false });
const contentBlockSchema = new mongoose.Schema({
    code: { type: String, required: true, trim: true, maxlength: 180 }, title: { type: String, required: true, trim: true, maxlength: 240 },
    courseId: { type: mongoose.Schema.Types.ObjectId, default: null, index: true }, lessonId: { type: mongoose.Schema.Types.ObjectId, default: null, index: true }, curriculumContentId: { type: mongoose.Schema.Types.ObjectId, default: null, index: true },
    type: { type: String, enum: ['OVERVIEW', 'THEORY', 'LECTURE', 'EXAMPLE', 'ACTIVITY', 'PRACTICE', 'CODE_CHALLENGE', 'QUIZ', 'SUMMARY', 'MEDIA', 'REFERENCE'], required: true, index: true },
    body: { type: String, default: '', maxlength: 200000 }, bodyFormat: { type: String, enum: ['PLAIN_TEXT', 'MARKDOWN', 'SANITIZED_HTML'], default: 'MARKDOWN' }, order: { type: Number, default: 0, min: 0 }, estimatedMinutes: { type: Number, default: 5, min: 0, max: 600 },
    skillCodes: { type: [String], default: [] }, prerequisiteSkillCodes: { type: [String], default: [] }, references: { type: [contentReferenceSchema], default: [] },
    sourceType: { type: String, enum: ['OFFICIAL', 'ADMIN_CREATED', 'AI_GENERATED', 'ORIGINAL_PRACTICE', 'SIMULATION', 'USER_IMPORTED'], default: 'ADMIN_CREATED' }, sourceVerified: { type: Boolean, default: false }, ownerUsername: { type: String, default: '' },
    status: { type: String, enum: ['DRAFT', 'REVIEW', 'PUBLISHED', 'ARCHIVED'], default: 'DRAFT', index: true }, version: { type: Number, default: 1, min: 1 },
    legacySourceId: { type: mongoose.Schema.Types.ObjectId, default: null }, legacyField: { type: String, default: '' }
}, options('contentBlocks'));
contentBlockSchema.index({ lessonId: 1, status: 1, order: 1 });
contentBlockSchema.index({ code: 1, version: 1 }, { unique: true });
const practiceSampleSchema = new mongoose.Schema({ input: { type: String, default: '', maxlength: 20000 }, expectedOutput: { type: String, required: true, maxlength: 20000 }, explanation: { type: String, default: '', maxlength: 4000 } }, { _id: false });
const practiceTestCaseSchema = new mongoose.Schema({ input: { type: String, default: '', maxlength: 20000 }, expectedOutput: { type: String, required: true, maxlength: 20000 }, weight: { type: Number, default: 1, min: 0, max: 100 } }, { _id: false });
const codeTemplateSchema = new mongoose.Schema({ language: { type: String, enum: ['javascript', 'python', 'c', 'cpp', 'java'], required: true }, code: { type: String, required: true, maxlength: 100000 } }, { _id: false });
const practiceTaskSchema = new mongoose.Schema({
    code: { type: String, required: true, trim: true, uppercase: true, maxlength: 100 }, title: { type: String, required: true, trim: true, maxlength: 220 }, description: { type: String, default: '', maxlength: 4000 },
    catalogTrack: { type: String, default: 'UNIVERSITY_IT', index: true }, courseId: { type: mongoose.Schema.Types.ObjectId, default: null, index: true }, lessonId: { type: mongoose.Schema.Types.ObjectId, default: null, index: true },
    language: { type: String, enum: ['javascript', 'python', 'c', 'cpp', 'java'], default: 'javascript' }, supportedLanguages: { type: [String], enum: ['javascript', 'python', 'c', 'cpp', 'java'], default: ['javascript'] },
    difficulty: { type: String, enum: ['BEGINNER', 'EASY', 'MEDIUM', 'HARD', 'EXPERT'], default: 'BEGINNER' }, topic: { type: String, default: '' }, skillCode: { type: String, required: true, index: true },
    statement: { type: String, required: true, maxlength: 50000 }, inputFormat: { type: String, default: '', maxlength: 10000 }, outputFormat: { type: String, default: '', maxlength: 10000 }, constraints: { type: [String], default: [] },
    samples: { type: [practiceSampleSchema], default: [] }, starterCode: { type: String, default: '', maxlength: 100000 }, starterCodeTemplates: { type: [codeTemplateSchema], default: [] }, functionSignature: { type: String, default: '', maxlength: 1000 }, executionMode: { type: String, enum: ['STDIN_STDOUT', 'FUNCTION'], default: 'STDIN_STDOUT' },
    visibleTestCases: { type: [practiceTestCaseSchema], default: [] }, hiddenTestCases: { type: [practiceTestCaseSchema], default: [] }, hints: { type: [String], default: [] }, solution: { type: String, default: '', maxlength: 100000 }, scoringCriteria: { type: [String], default: [] }, estimatedMinutes: { type: Number, default: 20, min: 1, max: 600 },
    sourceType: { type: String, enum: ['ADMIN_CREATED', 'AI_GENERATED', 'ORIGINAL_PRACTICE', 'SIMULATION', 'USER_IMPORTED'], default: 'ORIGINAL_PRACTICE' }, sourceVerified: { type: Boolean, default: false }, ownerUsername: { type: String, default: '' }, status: { type: String, enum: ['DRAFT', 'REVIEW', 'PUBLISHED', 'ARCHIVED'], default: 'DRAFT', index: true }, version: { type: Number, default: 1 }
}, options('practiceTasks'));
practiceTaskSchema.index({ code: 1 }, { unique: true });
practiceTaskSchema.index({ catalogTrack: 1, status: 1, skillCode: 1, difficulty: 1 });
const practiceAttemptSchema = new mongoose.Schema({ username: { type: String, required: true, index: true }, taskId: { type: mongoose.Schema.Types.ObjectId, required: true, index: true }, code: { type: String, required: true, maxlength: 512000 }, language: { type: String, required: true }, status: { type: String, enum: ['PASSED', 'PARTIAL', 'FAILED', 'RUNNER_DISABLED', 'REVIEW_REQUIRED'], required: true }, score: { type: Number, default: 0, min: 0, max: 100 }, scoreBreakdown: { earnedWeight: { type: Number, default: 0 }, possibleWeight: { type: Number, default: 0 }, visibleEarnedWeight: { type: Number, default: 0 }, visiblePossibleWeight: { type: Number, default: 0 }, hiddenEarnedWeight: { type: Number, default: 0 }, hiddenPossibleWeight: { type: Number, default: 0 } }, visiblePassed: { type: Number, default: 0 }, visibleTotal: { type: Number, default: 0 }, hiddenPassed: { type: Number, default: 0 }, hiddenTotal: { type: Number, default: 0 }, runtimeMs: { type: Number, default: 0 }, feedback: { type: [String], default: [] }, submittedAt: { type: Date, default: Date.now } }, options('practiceAttempts'));
practiceAttemptSchema.index({ username: 1, taskId: 1, submittedAt: -1 });
const learningPlanStepSchema = new mongoose.Schema({ username: { type: String, required: true, index: true }, planId: { type: mongoose.Schema.Types.ObjectId, required: true, index: true }, planVersion: { type: Number, required: true }, sequence: { type: Number, required: true, min: 1 }, kind: { type: String, enum: ['REVIEW', 'LESSON', 'PRACTICE', 'ASSESSMENT', 'PROJECT', 'COURSE_GAP'], required: true }, title: { type: String, required: true }, skillCode: { type: String, default: '', index: true }, currentLevel: { type: Number, default: 0, min: 0, max: 100 }, targetLevel: { type: Number, default: 80, min: 0, max: 100 }, gap: { type: Number, default: 0, min: 0, max: 100 }, priority: { type: Number, default: 50, min: 0, max: 100 }, courseId: mongoose.Schema.Types.ObjectId, lessonId: mongoose.Schema.Types.ObjectId, practiceTaskId: mongoose.Schema.Types.ObjectId, assessmentId: mongoose.Schema.Types.ObjectId, prerequisiteSkillCodes: { type: [String], default: [] }, reason: { type: String, default: '' }, estimatedMinutes: { type: Number, default: 15, min: 1, max: 600 }, status: { type: String, enum: ['LOCKED', 'READY', 'IN_PROGRESS', 'COMPLETED', 'REVIEW', 'COURSE_GAP'], default: 'READY', index: true }, dueAt: Date, completedAt: Date }, options('learningPlanSteps'));
learningPlanStepSchema.index({ username: 1, planId: 1, sequence: 1 }, { unique: true });
const learningEventSchema = new mongoose.Schema({ username: { type: String, required: true, index: true }, eventType: { type: String, enum: ['LESSON_STARTED', 'LESSON_COMPLETED', 'ASSESSMENT_SUBMITTED', 'PRACTICE_SUBMITTED', 'MASTERY_UPDATED', 'SURVEY_SUBMITTED', 'PLACEMENT_SUBMITTED', 'PLAN_GENERATED', 'REVIEW_DUE'], required: true, index: true }, entityType: { type: String, default: '' }, entityId: { type: String, default: '' }, skillCode: { type: String, default: '', index: true }, score: { type: Number, min: 0, max: 100 }, durationSeconds: { type: Number, min: 0, max: 86400 }, source: { type: String, default: 'SYSTEM' }, idempotencyKey: { type: String, default: '' }, occurredAt: { type: Date, default: Date.now, index: true }, metadata: { courseCode: String, lessonCode: String, attemptStatus: String, reason: String } }, options('learningEvents'));
const assignmentAttachmentSchema = new mongoose.Schema({ username: { type: String, required: true, index: true }, filename: { type: String, required: true, maxlength: 180 }, extension: { type: String, required: true, maxlength: 12 }, contentType: { type: String, required: true, maxlength: 120 }, size: { type: Number, required: true, min: 1, max: 3145728 }, data: { type: Buffer, required: true }, submissionId: { type: String, default: '', index: true }, deleteAfter: { type: Date, default: () => new Date(Date.now() + 86400000) } }, options('assignmentAttachments'));
assignmentAttachmentSchema.index({ deleteAfter: 1 }, { expireAfterSeconds: 0 });
const assignmentSubmissionSchema = new mongoose.Schema({ username: { type: String, required: true, index: true }, courseId: { type: String, default: '', index: true, maxlength: 120 }, courseCode: { type: String, default: '', maxlength: 120 }, lessonId: { type: String, required: true, index: true, maxlength: 120 }, taskTitle: { type: String, required: true, trim: true, maxlength: 240 }, taskIndex: { type: Number, min: 0, max: 500, default: 0 }, submissionText: { type: String, default: '', trim: true, maxlength: 20000 }, submissionUrl: { type: String, default: '', maxlength: 2048 }, attachmentId: { type: mongoose.Schema.Types.ObjectId, default: null }, attachmentFileName: { type: String, default: '', maxlength: 180 }, status: { type: String, enum: ['SUBMITTED', 'GRADED', 'RETURNED'], default: 'SUBMITTED', index: true }, score: { type: Number, min: 0, max: 100, default: null }, feedback: { type: String, default: '', maxlength: 5000 }, reviewerUsername: { type: String, default: '' }, submittedAt: { type: Date, default: Date.now, index: true }, gradedAt: Date }, options('assignmentSubmissions'));
assignmentSubmissionSchema.index({ username: 1, lessonId: 1, submittedAt: -1 });
assignmentSubmissionSchema.index({ status: 1, submittedAt: 1 });
learningEventSchema.index({ username: 1, idempotencyKey: 1 }, { unique: true, partialFilterExpression: { idempotencyKey: { $type: 'string', $gt: '' } } });
const essayGradingAttemptSchema = new mongoose.Schema({ username: { type: String, required: true, index: true }, grade: { type: Number, min: 1, max: 12, default: 1 }, subjectName: { type: String, default: 'Ngữ văn' }, prompt: { type: String, default: '', maxlength: 1000 }, essay: { type: String, required: true, maxlength: 12000 }, score: { type: Number, min: 0, max: 10, required: true }, criteria: { type: [mongoose.Schema.Types.Mixed], default: [] }, strengths: { type: [String], default: [] }, improvements: { type: [String], default: [] }, revisedExample: { type: String, default: '' }, source: { type: String, enum: ['gemini', 'openai', 'local', 'local-fallback'], default: 'local' }, feedback: { type: mongoose.Schema.Types.Mixed, default: {} } }, options('essayGradingAttempts'));
essayGradingAttemptSchema.index({ username: 1, createdAt: -1 });
const courseQualitySnapshotSchema = new mongoose.Schema({ courseId: { type: mongoose.Schema.Types.ObjectId, default: null, index: true }, courseCode: { type: String, default: '' }, courseTitle: { type: String, default: '' }, score: { type: Number, min: 0, max: 100, default: 0 }, status: { type: String, enum: ['PASS', 'NEEDS_REVIEW', 'FAIL'], default: 'FAIL', index: true }, lessonCount: { type: Number, default: 0 }, publishedLessonCount: { type: Number, default: 0 }, questionCount: { type: Number, default: 0 }, practiceCount: { type: Number, default: 0 }, issues: { type: [String], default: [] }, checkedBy: { type: String, default: '' }, checkedAt: { type: Date, default: Date.now } }, options('courseQualitySnapshots'));
courseQualitySnapshotSchema.index({ courseId: 1, checkedAt: -1 });

function model(name, schema) { return mongoose.models[name] || mongoose.model(name, schema); }
module.exports = {
    SourceRegistry: model('SourceRegistry', sourceRegistrySchema), Profile: model('Profile', profileSchema), EducationProfile: model('EducationProfile', educationProfileSchema), LearningProfile: model('PlatformLearningProfile', learningProfileSchema), CurriculumVersion: model('CurriculumVersion', curriculumVersionSchema), CurriculumContent: model('CurriculumContent', curriculumContentSchema),
    University: model('University', universitySchema), Faculty: model('Faculty', facultySchema), Field: model('Field', fieldSchema), DisciplineGroup: model('DisciplineGroup', disciplineGroupSchema), Major: model('Major', majorSchema), Specialization: model('Specialization', specializationSchema), TrainingProgram: model('TrainingProgram', trainingProgramSchema), Course: model('Course', courseSchema),
    Question: model('Question', questionSchema), Assessment: model('Assessment', assessmentSchema), AssessmentAttempt: model('AssessmentAttempt', assessmentAttemptSchema), Survey: model('Survey', surveySchema), SurveyAttempt: model('SurveyAttempt', surveyAttemptSchema), PlacementTest: model('PlacementTest', placementTestSchema), PlacementAttempt: model('PlacementAttempt', placementAttemptSchema), LearningPlan: model('LearningPlan', learningPlanSchema), LearningPathRule: model('LearningPathRule', learningPathRuleSchema), SkillMastery: model('SkillMastery', skillMasterySchema), EnglishTestConfig: model('EnglishTestConfig', englishTestConfigSchema), EnglishAssessment: model('EnglishAssessment', englishAssessmentSchema), ExamBlueprint: model('ExamBlueprint', examBlueprintSchema), WordImport: model('WordImport', wordImportSchema), Achievement: model('Achievement', achievementSchema), Reward: model('Reward', rewardSchema), UserAchievement: model('UserAchievement', userAchievementSchema), RewardGrant: model('RewardGrant', rewardGrantSchema), GamificationEvent: model('GamificationEvent', gamificationEventSchema), PlatformNotification: model('PlatformNotification', notificationSchema), AuditLog: model('AuditLog', auditLogSchema), AIContentDraft: model('AIContentDraft', aiContentDraftSchema), AIDecisionLog: model('AIDecisionLog', aiDecisionSchema), AIAudioAsset: model('AIAudioAsset', aiAudioAssetSchema), PersonalCourseNeed: model('PersonalCourseNeed', personalCourseNeedSchema), LearningError: model('LearningError', learningErrorSchema), AdaptivePracticeSession: model('AdaptivePracticeSession', adaptivePracticeSessionSchema), UserAudioAsset: model('UserAudioAsset', userAudioAssetSchema), AIImageAsset: model('AIImageAsset', aiImageAssetSchema), EnglishSpeakingAttempt: model('EnglishSpeakingAttempt', englishSpeakingAttemptSchema), AIGenerationJob: model('AIGenerationJob', aiGenerationJobSchema), CodeExecutionAttempt: model('CodeExecutionAttempt', codeExecutionAttemptSchema), LessonProgress: model('LessonProgress', lessonProgressSchema), AIAmbientInsight: model('AIAmbientInsight', aiAmbientInsightSchema), ContentBlock: model('ContentBlock', contentBlockSchema), PracticeTask: model('PracticeTask', practiceTaskSchema), PracticeAttempt: model('PracticeAttempt', practiceAttemptSchema), LearningPlanStep: model('LearningPlanStep', learningPlanStepSchema), LearningEvent: model('LearningEvent', learningEventSchema), AssignmentSubmission: model('AssignmentSubmission', assignmentSubmissionSchema), EssayGradingAttempt: model('EssayGradingAttempt', essayGradingAttemptSchema), AssignmentAttachment: model('AssignmentAttachment', assignmentAttachmentSchema), CourseQualitySnapshot: model('CourseQualitySnapshot', courseQualitySnapshotSchema)
};